gi:
{
    enabled: 1

    # max samples stored in history (shaded texel is actually maxSampleCount + 1)
    maxSampleCount: 64

    # absolute linear depth difference (in world units) above which history is rejected (disocclusion detection)
    historyDepthRejectionThreshold: 0.2
}

taa:
{
    enabled: 0
}
