# note: this file can't be reloaded.

#SceneSource: "media/sparrow.glb"
#SceneSource: "media/japanese-style-restaurant/export.glb"
SceneSource: "media/auto_export.glb"
#SceneSource: "media/cornell.glb"

LoadEnvironmentMap: 0
EnvironmentMap: "media/environment_maps/neon_photostudio_2k.exr"

AdditionalAssets:
[
    "media/export/sphere.glb"
]

Debug:
{
    # RenderDoc is not compatible with Vulkan validation layer and ray tracing... use NSight to debug ray tracing
    RenderDoc: 0

    # when launching from NSight Graphics, make sure validation layer is turned off or it'll crash
    ValidationLayer: 1

    AutoHotReload: 1

    CollapseSceneTree: 1

    # Options: "fifo", "fifo_relaxed", "mailbox", "immediate".
    # FIFO is always supported and vsynced. Mailbox/immediate are useful for diagnosing present pacing hitches.
    PresentMode: "fifo"
}