# note: this file can't be reloaded.

#SceneSource: "media/sparrow.glb"
#SceneSource: "media/japanese-style-restaurant/export.glb"
SceneSource: "media/auto_export.glb"
#SceneSource: "media/cornell.glb"

LoadEnvironmentMap: 0
EnvironmentMap: "media/environment_maps/neon_photostudio_2k.exr"

SkyAtmosphereDefaultEnabled: 1

AdditionalAssets:
[
    "media/export/sphere.glb"
]

Debug:
{
    # RenderDoc is not compatible with Vulkan validation layer and RTX... use NSight to debug RTX
    RenderDoc: 0

    RTX: 1

    # when launching from NSight Graphics, make sure validation layer is turned off or it'll crash
    ValidationLayer: 1

    AutoHotReload: 1

    CollapseSceneTree: 1
}