#version 460 core

#include "bindless_resources.glsl"

layout(set = 0, binding = 0, std430) readonly buffer BindlessSelfTestInput
{
    uint TextureIndices[2];
};

layout(set = 0, binding = 1, std430) writeonly buffer BindlessSelfTestOutput
{
    vec4 SampledColors[2];
};

layout(local_size_x = 2, local_size_y = 1, local_size_z = 1) in;

void main()
{
    uint invocation = gl_GlobalInvocationID.x;
    SampledColors[invocation] = sampleBindlessTexture2DLod(
        TextureIndices[invocation],
        vec2(0.5),
        0.0);
}
