#version 460 core
#extension GL_EXT_ray_query : require

#include "scene_common.glsl"
#include "sky_common.glsl"
#include "bindless_resources.glsl"

// (set 0, binding 0) is view info from scene_common.glsl
layout(set = 0, binding = 1) uniform sampler2D SceneDepth;
layout(set = 0, binding = 2) uniform sampler2D GNormal;
layout(set = 0, binding = 3) uniform accelerationStructureEXT SceneTLAS;
layout(set = 0, binding = 4, rgba16f) uniform writeonly image2D IndirectLighting;
layout(set = 0, binding = 5) uniform sampler2D EnvironmentMap;
layout(set = 0, binding = 6, std430) readonly buffer SceneInstanceRecordTable {
    GpuSceneInstanceRecord SceneInstanceRecords[];
};

// (set 1, binding 0) sky parameters
// (set 1, binding 8) transmittance
// (set 1, binding 9) skyview

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

vec3 buildTangent(vec3 normal)
{
    vec3 up = abs(normal.z) < 0.999 ? vec3(0.0, 0.0, 1.0) : vec3(0.0, 1.0, 0.0);
    return normalize(cross(up, normal));
}

vec3 sampleCosineWeightedHemisphere(vec3 normal, vec2 random)
{
    float r = sqrt(random.x);
    float phi = TWO_PI * random.y;
    vec3 localDir = vec3(r * cos(phi), r * sin(phi), sqrt(max(0.0, 1.0 - random.x)));

    vec3 tangent = buildTangent(normal);
    vec3 bitangent = cross(normal, tangent);
    return normalize(localDir.x * tangent + localDir.y * bitangent + localDir.z * normal);
}

vec3 sampleBackground(ViewInfo viewInfo, vec3 rayDir)
{
    if (viewInfo.BackgroundOption == 1) {
        return sampleLongLatMap(EnvironmentMap, rayDir, 0.0);
    }
    if (viewInfo.BackgroundOption == 2) {
        return sampleSkyAtmosphere(rayDir);
    }
    return vec3(0.0);
}

struct RayHitResult
{
    bool committed;
    uint intersectionType;
    uint instanceCustomIndex;
    uint primitiveIndex;
    vec2 barycentrics;
    float hitT;
};

RayHitResult makeMissHitResult()
{
    return RayHitResult(false, gl_RayQueryCommittedIntersectionNoneEXT, ~0u, ~0u, vec2(-1.0), -1.0);
}

RayHitResult traceRay(vec3 origin, vec3 direction)
{
    rayQueryEXT rq;
    rayQueryInitializeEXT(
        rq,
        SceneTLAS,
        // ray flags:
        0
        // | gl_RayFlagsTerminateOnFirstHitEXT // with this flag present, may terminate at ANY hit, not necessarily closest
        // | gl_RayFlagsSkipClosestHitShaderEXT // only relevant when in ray tracing pipeline
        | gl_RayFlagsOpaqueEXT,
        0xFF, // cull mask, see: https://github.com/KhronosGroup/GLSL/blob/d2470a0a124bbb8c90a3576aca94694bd2f789e0/extensions/ext/GLSL_EXT_ray_query.txt#L286
              // basically, the 8 bits will be combined with the mask field in VkAccelerationStructureInstanceKHR. Visible if result is non-zero.
        origin,
        0.001, // tmin
        direction,
        10000.0); // tmax
    rayQueryProceedEXT(rq);

    // the second boolean arg being true: want the final committed intersection
    // hit opaque triangle (forced by gl_RayFlagsOpaqueEXT, or VK_GEOMETRY_OPAQUE_BIT_KHR when building BLAS) -> internally confirmed
    // hit non-opaque triangle -> shader must confirm the hit
    // hit AABB (need BLAS to be built as procedural geometry not triangle geometry) -> shader must generate an intersection
    uint intersectionType = rayQueryGetIntersectionTypeEXT(rq, true);

    RayHitResult result = makeMissHitResult();
    if (intersectionType == gl_RayQueryCommittedIntersectionNoneEXT) {
        // it's a miss
        return result;
    }

    // it's a hit
    result.committed = true;

    // intersection types can be: None (miss), Triangle (triangle geometry), or Generated (AABB geometry), which is used for shader-defined procedural geometry
    result.intersectionType = intersectionType;

    result.instanceCustomIndex = rayQueryGetIntersectionInstanceCustomIndexEXT(rq, true);
    result.primitiveIndex = rayQueryGetIntersectionPrimitiveIndexEXT(rq, true);
    result.hitT = rayQueryGetIntersectionTEXT(rq, true);
    if (intersectionType == gl_RayQueryCommittedIntersectionTriangleEXT) {
        result.barycentrics = rayQueryGetIntersectionBarycentricsEXT(rq, true);
    }
    return result;
}

vec3 shadeCommittedHit(RayHitResult hitResult)
{
    if (hitResult.instanceCustomIndex == ~0u) {
        return vec3(0.0);
    }

    GpuSceneInstanceRecord sceneInstance = SceneInstanceRecords[hitResult.instanceCustomIndex];
    if (sceneInstance.bindlessMaterialIndex == INVALID_BINDLESS_INDEX) {
        return vec3(0.0);
    }

    GpuMaterial material = BindlessMaterials[sceneInstance.bindlessMaterialIndex];
    // DEBUG: now basically using baseColorFactor as emission
    return material.baseColorFactor.rgb * 0.05;
}

void main()
{
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    ivec2 dims = imageSize(IndirectLighting);
    if (pixel.x >= dims.x || pixel.y >= dims.y) {
        return;
    }

    float deviceDepth = texelFetch(SceneDepth, pixel, 0).r;
    vec3 normal = texelFetch(GNormal, pixel, 0).xyz;
    if (deviceDepth >= 1.0f) {
        // this texel is empty; doesn't contain hit surface that needs GI
        imageStore(IndirectLighting, pixel, vec4(0.0, 0.0, 0.0, 1.0));
        return;
    }

    normal = normalize(normal);
    ViewInfo viewInfo = GetViewInfo();
    vec2 random = vec2(
        white_noise01(uvec3(uvec2(pixel), viewInfo.FrameIndex), viewInfo.FrameRandom.x),
        white_noise01(uvec3(uvec2(pixel.yx), viewInfo.FrameIndex), viewInfo.FrameRandom.y));
    vec3 rayDir = sampleCosineWeightedHemisphere(normal, random);
    vec2 screenUv = (vec2(pixel) + 0.5f) / vec2(dims);
    vec3 rayOrigin = reconstructWorldPositionFromDepth(screenUv, deviceDepth, viewInfo) + normal * EPSILON;

    RayHitResult hitResult = traceRay(rayOrigin, rayDir);
    vec3 indirect = hitResult.committed ? shadeCommittedHit(hitResult) : sampleBackground(viewInfo, rayDir);
    imageStore(IndirectLighting, pixel, vec4(indirect, 1.0));
}
