#version 450

layout(set = 3, binding = 0, rgba16f) uniform writeonly image2D outImage;
layout(set = 3, binding = 1) uniform SkyAtmosphereParamsBufferObject {
    uvec2 transmittanceLutSize;
    uvec2 multiScatteredLutSize;
    uvec2 skyViewLutSize;
} skyAtmosphereParams;

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
void main()
{
    imageStore(outImage, ivec2(gl_GlobalInvocationID.xy), vec4(0.2, 0.3, 0.4, 1));
}